<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseAppHost>false</UseAppHost>

        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Astraia.Lobby</RootNamespace>

        <Nullable>disable</Nullable>
        <LangVersion>12</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <DebugType>None</DebugType>
        <OutputPath>../Astraia.Runtime/</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Astraia\Astraia.csproj"/>
    </ItemGroup>
</Project>
